# Generated by Django 5.2.7 on 2026-10-07 01:01

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=160)),
                ("message", models.TextField(max_length=4000)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Internal identifier used by templates, e.g. home.hero. Don't change existing keys.",
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9_.-]+$",
                                "Use lowercase letters, digits, dots, dashes.",
                            )
                        ],
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, max_length=120)),
                ("heading", models.CharField(blank=True, max_length=200)),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Blank line = new paragraph."
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="blocks/")),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Used when no file is uploaded.",
                        max_length=500,
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=160)),
                ("button_label", models.CharField(blank=True, max_length=60)),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        help_text="A URL or a page path such as /register/",
                        max_length=200,
                    ),
                ),
                (
                    "button_icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome name, e.g. fa-seedling",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
            bases=(core.models.ImageSourceMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=70, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "base_trees",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Trees planted before the website. Approved volunteer plantings are added on top.",
                    ),
                ),
                (
                    "map_note",
                    models.CharField(
                        blank=True,
                        help_text="Shown in the map popup, e.g. Urban & community plantation",
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "saplings",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ]
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Total in taka at the time of pledging."
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pledged", "Pledged"),
                            ("received", "Payment received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pledged",
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=60, unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "gallery categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="hero/")),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "alt",
                    models.CharField(
                        default="Tree planted by Green Bangladesh", max_length=160
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
            bases=(core.models.ImageSourceMixin, models.Model),
        ),
        migrations.CreateModel(
            name="InfoCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("home_features", "Home page — hero features"),
                            ("about_values", "About page — values"),
                            ("targets", "Mission page — 2030 targets"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome name, e.g. fa-seedling",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("text", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["group", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=140)),
                ("text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["year", "id"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=130, unique=True)),
                (
                    "tag",
                    models.CharField(
                        help_text="Small label on the card, e.g. Education",
                        max_length=40,
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Used on the home page slider.", max_length=220
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Used on the Programs page."),
                ),
                ("image", models.ImageField(blank=True, upload_to="programs/")),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "show_on_home",
                    models.BooleanField(
                        default=True, help_text="Show in the home-page slider."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "short_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional shorter title for the home slider.",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
            bases=(core.models.ImageSourceMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Green Bangladesh", max_length=80),
                ),
                (
                    "footer_blurb",
                    models.TextField(
                        default="Working together to make Bangladesh greener through tree plantation, environmental awareness and community participation."
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="House 14, Road 7, Dhanmondi, Dhaka, Bangladesh",
                        max_length=200,
                    ),
                ),
                (
                    "short_address",
                    models.CharField(default="Dhaka, Bangladesh", max_length=100),
                ),
                ("phone", models.CharField(default="+880 1XXX-XXXXXX", max_length=60)),
                (
                    "phone_hours",
                    models.CharField(
                        blank=True, default="10am–6pm, Sat–Thu", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@greenbangladesh.org", max_length=254
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "baseline_registered_users",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Volunteers who joined before this website. Real registrations are added to this.",
                    ),
                ),
                ("active_teams", models.PositiveIntegerField(default=0)),
                (
                    "sapling_cost",
                    models.PositiveIntegerField(
                        default=150,
                        help_text="Cost of one sapling in taka (used on the donate page).",
                    ),
                ),
                ("mission_text", models.TextField(blank=True)),
                ("vision_text", models.TextField(blank=True)),
                (
                    "contact_notify_email",
                    models.EmailField(
                        blank=True,
                        help_text="Receive an email for every contact message and donation pledge (optional).",
                        max_length=254,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="GalleryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=140)),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                ("image", models.ImageField(blank=True, upload_to="gallery/")),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "layout",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Normal"),
                            ("wide", "Wide"),
                            ("tall", "Tall"),
                            ("wide tall", "Wide and tall"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="core.gallerycategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at", "-id"],
            },
            bases=(core.models.ImageSourceMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TreePlanting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(blank=True, max_length=80)),
                (
                    "trees_count",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Village, upazila or landmark",
                        max_length=160,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="plantings/")),
                (
                    "planted_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("admin_note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plantings",
                        to="core.division",
                    ),
                ),
                (
                    "gallery_photo",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planting",
                        to="core.galleryphoto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
