# Generated by Django 5.2.7 on 2026-10-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Replaces the seedling icon in the header, footer and login pages. Transparent PNG/SVG-like images work best; also used as the browser tab icon.",
                upload_to="branding/",
            ),
        ),
    ]
