# Generated by Django 5.2.7 on 2026-10-07 02:13

from django.db import migrations, models


def copy_social_links(apps, schema_editor):
    """Keep any social URLs already saved in Site settings."""
    Settings = apps.get_model("core", "SiteSettings")
    Social = apps.get_model("core", "SocialLink")
    row = Settings.objects.first()
    if not row:
        return
    for i, (name, icon, field) in enumerate([
        ("Facebook", "fab fa-facebook-f", "facebook_url"), ("YouTube", "fab fa-youtube", "youtube_url"),
        ("Instagram", "fab fa-instagram", "instagram_url"), ("LinkedIn", "fab fa-linkedin-in", "linkedin_url"),
    ]):
        url = getattr(row, field, "")
        if url:
            Social.objects.create(name=name, icon=icon, url=url, order=i)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu",
                    models.CharField(
                        choices=[
                            ("main", "Main navigation (header + mobile menu)"),
                            (
                                "actions",
                                "Header buttons (log in / register / dashboard / log out)",
                            ),
                            ("footer_explore", "Footer — first link column"),
                            ("footer_account", "Footer — second link column"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                (
                    "url",
                    models.CharField(
                        help_text="A page path such as /about/ or a full https:// address.",
                        max_length=300,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome classes, e.g. fa-solid fa-right-to-bracket",
                        max_length=60,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("always", "Everyone"),
                            ("anonymous", "Only visitors who are logged out"),
                            ("authenticated", "Only logged-in users"),
                        ],
                        default="always",
                        max_length=15,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("link", "Plain link"),
                            ("line", "Outline button"),
                            ("primary", "Filled button"),
                        ],
                        default="link",
                        help_text="Only used for header buttons.",
                        max_length=10,
                    ),
                ),
                (
                    "is_logout",
                    models.BooleanField(
                        default=False,
                        help_text="Makes this item a secure log-out button.",
                    ),
                ),
                ("new_tab", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["menu", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Identifier used by the templates. Don't rename.",
                        max_length=160,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="Text shown on the site. {placeholders} such as {site_name} are filled in automatically — keep them.",
                    ),
                ),
                ("default", models.TextField(blank=True, editable=False)),
                (
                    "group",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=40
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site text",
                "verbose_name_plural": "Site texts (all interface wording)",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Used for screen readers, e.g. Facebook",
                        max_length=40,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fab fa-facebook-f",
                        help_text="Font Awesome classes, e.g. fab fa-youtube",
                        max_length=60,
                    ),
                ),
                ("url", models.URLField(max_length=300)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "users",
                                "Live: registered volunteers (baseline + real sign-ups)",
                            ),
                            (
                                "trees",
                                "Live: trees planted (divisions + approved plantings)",
                            ),
                            ("teams", "Active teams (number in Site settings)"),
                            ("plantings", "Live: approved planting reports"),
                            ("manual", "A number I type in below"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                (
                    "manual_value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Only used when the source is 'A number I type in'.",
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        default="+",
                        help_text="Shown after the number, e.g. +",
                        max_length=8,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(copy_social_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="sitesettings",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="youtube_url",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="currency_symbol",
            field=models.CharField(default="৳", max_length=8),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="sapling_cost",
            field=models.PositiveIntegerField(
                default=150, help_text="Cost of one sapling (used on the donate page)."
            ),
        ),
    ]
