# Generated by Django 5.2.7 on 2026-10-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dynamic_texts_menus_social_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Small square icon for the browser tab (use the emblem only). If empty, the logo is used.",
                upload_to="branding/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_name_with_logo",
            field=models.BooleanField(
                default=False,
                help_text="Tick to print the site name next to the logo. Leave off when the logo already contains the name.",
            ),
        ),
    ]
