# Generated by Django 5.2.7 on 2026-10-07 06:57

import django.core.validators
from django.db import migrations, models


def upgrade_existing(apps, schema_editor):
    """Show the name beside the logo and request sharper photos for the larger hero strip."""
    apps.get_model("core", "SiteSettings").objects.update(show_name_with_logo=True)
    Hero = apps.get_model("core", "HeroImage")
    for h in Hero.objects.filter(image_url__contains="images.unsplash.com"):
        if "w=400" in h.image_url:
            h.image_url = h.image_url.replace("w=400", "w=800")
            h.save(update_fields=["image_url"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings_favicon_name_toggle"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_strip_scale",
            field=models.PositiveSmallIntegerField(
                default=150,
                help_text="Size of the sliding photos on the home page, in percent (100 = original size, 150 = 1.5 times wider and taller).",
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="show_name_with_logo",
            field=models.BooleanField(
                default=True,
                help_text="Show the site name next to the logo in the header and footer.",
            ),
        ),
        migrations.RunPython(upgrade_existing, migrations.RunPython.noop),
    ]
