# Generated by Django 5.2.7 on 2026-10-07 07:11

import django.core.validators
from django.db import migrations, models


def enlarge(apps, schema_editor):
    """Move installs still on the previous default (150%) to the new, larger default and use sharper photos."""
    apps.get_model("core", "SiteSettings").objects.filter(hero_strip_scale=150).update(hero_strip_scale=220)
    Hero = apps.get_model("core", "HeroImage")
    for h in Hero.objects.filter(image_url__contains="images.unsplash.com"):
        if "w=400" in h.image_url or "w=800" in h.image_url:
            h.image_url = h.image_url.replace("w=400", "w=1200").replace("w=800", "w=1200")
            h.save(update_fields=["image_url"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_hero_scale_name_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_strip_scale",
            field=models.PositiveSmallIntegerField(
                default=220,
                help_text="Size of the sliding photos on the home page, in percent (100 = original size, 220 = 2.2 times wider and taller, 300 = maximum).",
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.RunPython(enlarge, migrations.RunPython.noop),
    ]
