# Generated by Django 5.2.7 on 2026-10-08 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_hero_scale_larger"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="google_map_id",
            field=models.CharField(
                blank=True,
                default="DEMO_MAP_ID",
                help_text="Optional Google 'Map ID' (Cloud Console → Map Management) if you want a custom map style. Leave DEMO_MAP_ID otherwise.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_maps_api_key",
            field=models.CharField(
                blank=True,
                help_text="Google Maps JavaScript API key. Create one at console.cloud.google.com → APIs & Services → Credentials, enable 'Maps JavaScript API', and restrict the key to your website address (HTTP referrers). Without a key the site shows a simple Google Maps embed instead of the interactive map with markers.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="map_center_lat",
            field=models.FloatField(
                default=23.8, help_text="Latitude the map opens on."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="map_center_lng",
            field=models.FloatField(
                default=90.3, help_text="Longitude the map opens on."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="map_fallback_query",
            field=models.CharField(
                default="Bangladesh",
                help_text="Place shown in the simple Google Maps embed when no API key is set.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="map_zoom",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="1 = whole world, 7 = a country, 15 = streets.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(18),
                ],
            ),
        ),
    ]
